USE [master]
GO
/****** Object:  Database [HYDRA]    Script Date: 8/20/2025 2:53:44 PM ******/
CREATE DATABASE [HYDRA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HYDRA', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\HYDRA.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'HYDRA_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\HYDRA_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [HYDRA] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HYDRA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [HYDRA] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [HYDRA] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [HYDRA] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [HYDRA] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [HYDRA] SET ARITHABORT OFF 
GO
ALTER DATABASE [HYDRA] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [HYDRA] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [HYDRA] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [HYDRA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [HYDRA] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [HYDRA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [HYDRA] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [HYDRA] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [HYDRA] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [HYDRA] SET  ENABLE_BROKER 
GO
ALTER DATABASE [HYDRA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [HYDRA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [HYDRA] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [HYDRA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [HYDRA] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [HYDRA] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [HYDRA] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [HYDRA] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [HYDRA] SET  MULTI_USER 
GO
ALTER DATABASE [HYDRA] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [HYDRA] SET DB_CHAINING OFF 
GO
ALTER DATABASE [HYDRA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [HYDRA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [HYDRA] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [HYDRA] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [HYDRA] SET QUERY_STORE = ON
GO
ALTER DATABASE [HYDRA] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [HYDRA]
GO
/****** Object:  Table [dbo].[CartItems]    Script Date: 8/20/2025 2:53:44 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CartItems](
	[CartItemID] [int] IDENTITY(1,1) NOT NULL,
	[CartID] [int] NOT NULL,
	[GameID] [int] NOT NULL,
	[DateAdded] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_CartItems] PRIMARY KEY CLUSTERED 
(
	[CartItemID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Companies]    Script Date: 8/20/2025 2:53:44 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Companies](
	[CompanyID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](150) NOT NULL,
 CONSTRAINT [PK_Companies] PRIMARY KEY CLUSTERED 
(
	[CompanyID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[GameDevelopers]    Script Date: 8/20/2025 2:53:44 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GameDevelopers](
	[GameID] [int] NOT NULL,
	[DeveloperID] [int] NOT NULL,
 CONSTRAINT [PK_GameDevelopers] PRIMARY KEY CLUSTERED 
(
	[GameID] ASC,
	[DeveloperID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[GameGenres]    Script Date: 8/20/2025 2:53:44 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GameGenres](
	[GameID] [int] NOT NULL,
	[GenreID] [int] NOT NULL,
 CONSTRAINT [PK_GameGenres] PRIMARY KEY CLUSTERED 
(
	[GameID] ASC,
	[GenreID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[GameImages]    Script Date: 8/20/2025 2:53:44 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GameImages](
	[ImageID] [int] IDENTITY(1,1) NOT NULL,
	[GameID] [int] NOT NULL,
	[ImagePath] [nvarchar](512) NOT NULL,
	[Description] [nvarchar](255) NULL,
 CONSTRAINT [PK_GameImages] PRIMARY KEY CLUSTERED 
(
	[ImageID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[GamePlatforms]    Script Date: 8/20/2025 2:53:44 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GamePlatforms](
	[GameID] [int] NOT NULL,
	[PlatformID] [int] NOT NULL,
 CONSTRAINT [PK_GamePlatforms] PRIMARY KEY CLUSTERED 
(
	[GameID] ASC,
	[PlatformID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Games]    Script Date: 8/20/2025 2:53:44 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Games](
	[GameID] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](255) NOT NULL,
	[Description] [nvarchar](max) NULL,
	[ReleaseDate] [date] NULL,
	[CoverArtPath] [nvarchar](512) NULL,
	[PublisherID] [int] NULL,
	[Price] [decimal](10, 2) NOT NULL,
	[IsForSale] [bit] NOT NULL,
 CONSTRAINT [PK_Games] PRIMARY KEY CLUSTERED 
(
	[GameID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[GameSuggestions]    Script Date: 8/20/2025 2:53:44 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GameSuggestions](
	[SuggestionID] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](255) NOT NULL,
	[PlatformText] [nvarchar](255) NULL,
	[Description] [nvarchar](max) NULL,
	[CreatedByUserID] [int] NOT NULL,
	[CreatedAt] [datetime2](7) NOT NULL,
	[Status] [tinyint] NOT NULL,
	[ApprovedByUserID] [int] NULL,
	[ApprovedAt] [datetime2](7) NULL,
	[ApprovedNote] [nvarchar](1000) NULL,
	[RawgId] [int] NULL,
	[RawgSlug] [nvarchar](200) NULL,
	[RawgName] [nvarchar](255) NULL,
	[RawgReleased] [date] NULL,
	[RawgMetacritic] [int] NULL,
	[RawgBackgroundImg] [nvarchar](600) NULL,
	[RawgPlatforms] [nvarchar](600) NULL,
	[RawgGenres] [nvarchar](400) NULL,
	[RawgPublishers] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[SuggestionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[GameSuggestionVotes]    Script Date: 8/20/2025 2:53:44 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GameSuggestionVotes](
	[SuggestionID] [int] NOT NULL,
	[UserID] [int] NOT NULL,
	[VotedAt] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_GameSuggestionVotes] PRIMARY KEY CLUSTERED 
(
	[SuggestionID] ASC,
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Genres]    Script Date: 8/20/2025 2:53:44 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Genres](
	[GenreID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_Genres] PRIMARY KEY CLUSTERED 
(
	[GenreID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LibraryEntries]    Script Date: 8/20/2025 2:53:44 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LibraryEntries](
	[LibraryEntryID] [int] IDENTITY(1,1) NOT NULL,
	[UserID] [int] NOT NULL,
	[GameID] [int] NOT NULL,
	[StatusID] [int] NOT NULL,
	[UserRating] [int] NULL,
	[HoursPlayed] [decimal](7, 2) NULL,
	[Notes] [nvarchar](max) NULL,
	[DateAdded] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_LibraryEntries] PRIMARY KEY CLUSTERED 
(
	[LibraryEntryID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[OrderItems]    Script Date: 8/20/2025 2:53:44 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[OrderItems](
	[OrderItemID] [int] IDENTITY(1,1) NOT NULL,
	[OrderID] [int] NOT NULL,
	[GameID] [int] NOT NULL,
	[PriceAtTimeOfPurchase] [decimal](10, 2) NOT NULL,
 CONSTRAINT [PK_OrderItems] PRIMARY KEY CLUSTERED 
(
	[OrderItemID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Orders]    Script Date: 8/20/2025 2:53:44 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Orders](
	[OrderID] [int] IDENTITY(1,1) NOT NULL,
	[UserID] [int] NOT NULL,
	[OrderDate] [datetime2](7) NOT NULL,
	[TotalAmount] [decimal](10, 2) NOT NULL,
 CONSTRAINT [PK_Orders] PRIMARY KEY CLUSTERED 
(
	[OrderID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Platforms]    Script Date: 8/20/2025 2:53:44 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Platforms](
	[PlatformID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_Platforms] PRIMARY KEY CLUSTERED 
(
	[PlatformID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Roles]    Script Date: 8/20/2025 2:53:44 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Roles](
	[RoleID] [int] IDENTITY(1,1) NOT NULL,
	[RoleName] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Roles] PRIMARY KEY CLUSTERED 
(
	[RoleID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[RoleName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ShoppingCarts]    Script Date: 8/20/2025 2:53:44 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ShoppingCarts](
	[CartID] [int] IDENTITY(1,1) NOT NULL,
	[UserID] [int] NOT NULL,
	[DateCreated] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_ShoppingCarts] PRIMARY KEY CLUSTERED 
(
	[CartID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Statuses]    Script Date: 8/20/2025 2:53:44 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Statuses](
	[StatusID] [int] IDENTITY(1,1) NOT NULL,
	[StatusName] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Statuses] PRIMARY KEY CLUSTERED 
(
	[StatusID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[StatusName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 8/20/2025 2:53:44 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[UserID] [int] IDENTITY(1,1) NOT NULL,
	[Username] [nvarchar](100) NOT NULL,
	[Email] [nvarchar](255) NOT NULL,
	[HashedPassword] [nvarchar](max) NOT NULL,
	[DateCreated] [datetime2](7) NOT NULL,
	[RoleID] [int] NOT NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Index [IX_GameSuggestions_RawgId]    Script Date: 8/20/2025 2:53:44 PM ******/
CREATE NONCLUSTERED INDEX [IX_GameSuggestions_RawgId] ON [dbo].[GameSuggestions]
(
	[RawgId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_GameSuggestionVotes_SuggestionId_UserId]    Script Date: 8/20/2025 2:53:44 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_GameSuggestionVotes_SuggestionId_UserId] ON [dbo].[GameSuggestionVotes]
(
	[SuggestionID] ASC,
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CartItems] ADD  DEFAULT (getdate()) FOR [DateAdded]
GO
ALTER TABLE [dbo].[Games] ADD  DEFAULT ((0.00)) FOR [Price]
GO
ALTER TABLE [dbo].[Games] ADD  DEFAULT ((1)) FOR [IsForSale]
GO
ALTER TABLE [dbo].[GameSuggestions] ADD  DEFAULT (sysutcdatetime()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[GameSuggestions] ADD  DEFAULT ((0)) FOR [Status]
GO
ALTER TABLE [dbo].[GameSuggestionVotes] ADD  DEFAULT (sysutcdatetime()) FOR [VotedAt]
GO
ALTER TABLE [dbo].[LibraryEntries] ADD  DEFAULT (getdate()) FOR [DateAdded]
GO
ALTER TABLE [dbo].[Orders] ADD  DEFAULT (getdate()) FOR [OrderDate]
GO
ALTER TABLE [dbo].[ShoppingCarts] ADD  DEFAULT (getdate()) FOR [DateCreated]
GO
ALTER TABLE [dbo].[Users] ADD  DEFAULT (getdate()) FOR [DateCreated]
GO
ALTER TABLE [dbo].[Users] ADD  DEFAULT ((1)) FOR [RoleID]
GO
ALTER TABLE [dbo].[CartItems]  WITH CHECK ADD  CONSTRAINT [FK_CartItems_Games] FOREIGN KEY([GameID])
REFERENCES [dbo].[Games] ([GameID])
GO
ALTER TABLE [dbo].[CartItems] CHECK CONSTRAINT [FK_CartItems_Games]
GO
ALTER TABLE [dbo].[CartItems]  WITH CHECK ADD  CONSTRAINT [FK_CartItems_ShoppingCarts] FOREIGN KEY([CartID])
REFERENCES [dbo].[ShoppingCarts] ([CartID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[CartItems] CHECK CONSTRAINT [FK_CartItems_ShoppingCarts]
GO
ALTER TABLE [dbo].[GameDevelopers]  WITH CHECK ADD  CONSTRAINT [FK_GameDevelopers_Companies] FOREIGN KEY([DeveloperID])
REFERENCES [dbo].[Companies] ([CompanyID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[GameDevelopers] CHECK CONSTRAINT [FK_GameDevelopers_Companies]
GO
ALTER TABLE [dbo].[GameDevelopers]  WITH CHECK ADD  CONSTRAINT [FK_GameDevelopers_Games] FOREIGN KEY([GameID])
REFERENCES [dbo].[Games] ([GameID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[GameDevelopers] CHECK CONSTRAINT [FK_GameDevelopers_Games]
GO
ALTER TABLE [dbo].[GameGenres]  WITH CHECK ADD  CONSTRAINT [FK_GameGenres_Games] FOREIGN KEY([GameID])
REFERENCES [dbo].[Games] ([GameID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[GameGenres] CHECK CONSTRAINT [FK_GameGenres_Games]
GO
ALTER TABLE [dbo].[GameGenres]  WITH CHECK ADD  CONSTRAINT [FK_GameGenres_Genres] FOREIGN KEY([GenreID])
REFERENCES [dbo].[Genres] ([GenreID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[GameGenres] CHECK CONSTRAINT [FK_GameGenres_Genres]
GO
ALTER TABLE [dbo].[GameImages]  WITH CHECK ADD  CONSTRAINT [FK_GameImages_Games] FOREIGN KEY([GameID])
REFERENCES [dbo].[Games] ([GameID])
GO
ALTER TABLE [dbo].[GameImages] CHECK CONSTRAINT [FK_GameImages_Games]
GO
ALTER TABLE [dbo].[GamePlatforms]  WITH CHECK ADD  CONSTRAINT [FK_GamePlatforms_Games] FOREIGN KEY([GameID])
REFERENCES [dbo].[Games] ([GameID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[GamePlatforms] CHECK CONSTRAINT [FK_GamePlatforms_Games]
GO
ALTER TABLE [dbo].[GamePlatforms]  WITH CHECK ADD  CONSTRAINT [FK_GamePlatforms_Platforms] FOREIGN KEY([PlatformID])
REFERENCES [dbo].[Platforms] ([PlatformID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[GamePlatforms] CHECK CONSTRAINT [FK_GamePlatforms_Platforms]
GO
ALTER TABLE [dbo].[Games]  WITH CHECK ADD  CONSTRAINT [FK_Games_Companies] FOREIGN KEY([PublisherID])
REFERENCES [dbo].[Companies] ([CompanyID])
GO
ALTER TABLE [dbo].[Games] CHECK CONSTRAINT [FK_Games_Companies]
GO
ALTER TABLE [dbo].[GameSuggestions]  WITH CHECK ADD  CONSTRAINT [FK_GameSuggestions_Users_ApprovedBy] FOREIGN KEY([ApprovedByUserID])
REFERENCES [dbo].[Users] ([UserID])
GO
ALTER TABLE [dbo].[GameSuggestions] CHECK CONSTRAINT [FK_GameSuggestions_Users_ApprovedBy]
GO
ALTER TABLE [dbo].[GameSuggestions]  WITH CHECK ADD  CONSTRAINT [FK_GameSuggestions_Users_CreatedBy] FOREIGN KEY([CreatedByUserID])
REFERENCES [dbo].[Users] ([UserID])
GO
ALTER TABLE [dbo].[GameSuggestions] CHECK CONSTRAINT [FK_GameSuggestions_Users_CreatedBy]
GO
ALTER TABLE [dbo].[GameSuggestionVotes]  WITH CHECK ADD  CONSTRAINT [FK_GameSuggestionVotes_Suggestion] FOREIGN KEY([SuggestionID])
REFERENCES [dbo].[GameSuggestions] ([SuggestionID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[GameSuggestionVotes] CHECK CONSTRAINT [FK_GameSuggestionVotes_Suggestion]
GO
ALTER TABLE [dbo].[GameSuggestionVotes]  WITH CHECK ADD  CONSTRAINT [FK_GameSuggestionVotes_User] FOREIGN KEY([UserID])
REFERENCES [dbo].[Users] ([UserID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[GameSuggestionVotes] CHECK CONSTRAINT [FK_GameSuggestionVotes_User]
GO
ALTER TABLE [dbo].[LibraryEntries]  WITH CHECK ADD  CONSTRAINT [FK_LibraryEntries_Games] FOREIGN KEY([GameID])
REFERENCES [dbo].[Games] ([GameID])
GO
ALTER TABLE [dbo].[LibraryEntries] CHECK CONSTRAINT [FK_LibraryEntries_Games]
GO
ALTER TABLE [dbo].[LibraryEntries]  WITH CHECK ADD  CONSTRAINT [FK_LibraryEntries_Statuses] FOREIGN KEY([StatusID])
REFERENCES [dbo].[Statuses] ([StatusID])
GO
ALTER TABLE [dbo].[LibraryEntries] CHECK CONSTRAINT [FK_LibraryEntries_Statuses]
GO
ALTER TABLE [dbo].[LibraryEntries]  WITH CHECK ADD  CONSTRAINT [FK_LibraryEntries_Users] FOREIGN KEY([UserID])
REFERENCES [dbo].[Users] ([UserID])
GO
ALTER TABLE [dbo].[LibraryEntries] CHECK CONSTRAINT [FK_LibraryEntries_Users]
GO
ALTER TABLE [dbo].[OrderItems]  WITH CHECK ADD  CONSTRAINT [FK_OrderItems_Games] FOREIGN KEY([GameID])
REFERENCES [dbo].[Games] ([GameID])
GO
ALTER TABLE [dbo].[OrderItems] CHECK CONSTRAINT [FK_OrderItems_Games]
GO
ALTER TABLE [dbo].[OrderItems]  WITH CHECK ADD  CONSTRAINT [FK_OrderItems_Orders] FOREIGN KEY([OrderID])
REFERENCES [dbo].[Orders] ([OrderID])
GO
ALTER TABLE [dbo].[OrderItems] CHECK CONSTRAINT [FK_OrderItems_Orders]
GO
ALTER TABLE [dbo].[Orders]  WITH CHECK ADD  CONSTRAINT [FK_Orders_Users] FOREIGN KEY([UserID])
REFERENCES [dbo].[Users] ([UserID])
GO
ALTER TABLE [dbo].[Orders] CHECK CONSTRAINT [FK_Orders_Users]
GO
ALTER TABLE [dbo].[ShoppingCarts]  WITH CHECK ADD  CONSTRAINT [FK_ShoppingCarts_Users] FOREIGN KEY([UserID])
REFERENCES [dbo].[Users] ([UserID])
GO
ALTER TABLE [dbo].[ShoppingCarts] CHECK CONSTRAINT [FK_ShoppingCarts_Users]
GO
ALTER TABLE [dbo].[Users]  WITH CHECK ADD  CONSTRAINT [FK_Users_Roles] FOREIGN KEY([RoleID])
REFERENCES [dbo].[Roles] ([RoleID])
GO
ALTER TABLE [dbo].[Users] CHECK CONSTRAINT [FK_Users_Roles]
GO
ALTER TABLE [dbo].[LibraryEntries]  WITH CHECK ADD  CONSTRAINT [CK_UserRating] CHECK  (([UserRating] IS NULL OR [UserRating]>=(1) AND [UserRating]<=(10)))
GO
ALTER TABLE [dbo].[LibraryEntries] CHECK CONSTRAINT [CK_UserRating]
GO
USE [master]
GO
ALTER DATABASE [HYDRA] SET  READ_WRITE 
GO
